multilambda/urls.py
from django.conf.urls import url

from . import views

app_name = 'multilambda'
urlpatterns = [
    url(r'^form/', views.form, name='form'),
    url(r'^submit/', views.submit, name='submit'),
    url(r'^(?P<taskname>.*)/status/', views.status, name='status'),
    url(r'^(?P<taskname>.*)/webpage/', views.webpage, name='webpage'),
]

webinterface/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url(r'^multilambda/', include('multilambda.urls')),
    path('admin/', admin.site.urls),
]

atel/models.py
from statistics import mode
from django.db import models

# Create your models here.
class AtelSub(models.Model):
    subject = models.CharField(max_length=200)

    def __str__(self):
        return self.subject

class AtelSource(models.Model):
    srcra = models.FloatField('R.A. of the source')
    srcdec = models.FloatField('Decl. of the source')
    taskname = models.CharField(max_length=200)

    def __str__(self):
        return f'AtelSrc#{self.pk}'

class AtelMain(models.Model):
    atelID = models.IntegerField('ATel ID', primary_key=True)
    atelSub = models.ManyToManyField(AtelSub)
    atelSrc = models.ManyToManyField(AtelSource)

    def __str__(self):
        return f'ATel#{self.atelID}'

multilambda/models.py
from django.db import models

# Create your models here.
class SourceWeb(models.Model):
    taskname = models.CharField(max_length=200)
    taskdate = models.DateTimeField('Date task was submitted')
    srcra = models.FloatField('R.A. of the source')
    srcdec = models.FloatField('Decl. of the source')
    fileExist = models.BooleanField('Whether the file is still existed')

    def __str__(self):
        return self.taskname

atel/views.py
from django.shortcuts import render

# Create your views here.

multilambda/views.py
### django related packages
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .config import *

#
from . import utils

# Create your views here.
def form(request):
    '''
    html form for the source to be analyzed
    '''
    instrumentForm = utils._loadinstruments_()
    return render(request, 'multilambda/form.html', {'instrumentForm': instrumentForm})

def submit(request):
    ### dev version to show the submit page ###
    # request_post = utils._parserequest_(request)
    # request_post = request.POST
    # return render(request, 'multilambda/submit.html', {'request_post':request_post})
    ### normal version for submission
    request_info = utils._parserequest_(request)
    taskname = utils._assigntask_(request_info['coord'])
    utils._savejson_(request_info, taskname, 'request.info')
    ## open a backgroud thread ##
    ## warning!!! this may cause DoS attack ##
    utils._openthread_(
        utils._sourceanalysis_,
        args = (request_info['coord'], taskname, request_info['todownload'])
    )
    return HttpResponseRedirect(reverse('multilambda:status', args=(taskname,)))

def status(request, taskname):
    statusjson = utils._checkdownloadstatus_(taskname)
    return render(request, 'multilambda/status.html', {'taskname':taskname, 'statusjson':statusjson})
    
def webpage(request, taskname):
    requestjson = utils._loadrequestjson_(taskname, filenameconvert=True)
    ra, dec = requestjson['coord']
    overlaypath = utils._getmulticutoutpath_(taskname)
    isvast = utils._checkmeasure_(taskname)
    vasttab = utils._loadVASTtab_(taskname)
    return render(
        request, 'multilambda/webpage.html', 
        {
            'taskname':taskname,
            'ra':ra, 'dec':dec,
            'overlaypath': overlaypath,
            'isvast': isvast,
            'vasttab': vasttab
        }
    )

multilambda/templates/multilambda/form.html
<!-- css part -->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'multilambda/formstyle.css' %}" />
<!-- end of css part -->

<h1> Multiwavelength Image Query </h1>

<form action = "{% url 'multilambda:submit' %}" method="post">
    {% csrf_token %}
    <!-- coordinate input -->
    coordinate: <input type="text" name="coord" />
    <input type="radio" name="coord_box" id="radeccheck" value="1" checked="checked" />
    <label for="radeccheck">J2000</label>
    <input type="radio" name="coord_box" id="glcheck" value="2"/>
    <label for="glcheck">Gal</label> <hr />
    {% for band, radius, surveys in instrumentForm %} 
        <font id="band"> {{band}} </font> 
        <font> radius </font>
        <input type="text" name="{{band}}_r" size="3" value={{radius}} />
        <font> (arcsec) </font>
        <p />
        {% for survey in surveys %}
            <input type="checkbox" name="{{band}}" id="{{band}}{{forloop.counter}}" value="{{forloop.counter}}" checked="checked"/>
            <label for="{{band}}{{forloop.counter}}">{{survey}}</label>
        {% endfor %}
        <hr />
    {% endfor %}

<p><input type="submit" value = "submit" /></p>
</form>

multilambda/templates/multilambda/status.html
<meta http-equiv="refresh" content="10">

<h1>status page for task {{taskname}}</h1>

<ul>
    {%for event, status in statusjson.items%}
    <li>{{event}} - {{status}}</li>
    {% endfor %}
</ul>

<p>Note: this page will be automatically refreshed every 10 seconds</p>
<p>click <a href="{% url 'multilambda:webpage' taskname %}">this link</a> for the full information</p>

multilambda/templates/multilambda/submit.html
<h3>Reuqest Post</h3>

<p>{{request_post}}</p>

multilambda/templates/multilambda/webpage.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!-- see https://docs.djangoproject.com/en/dev/ref/templates/builtins/#get-static-prefix -->
<link rel="stylesheet" type="text/css" href="{% static 'multilambda/webpagestyle.css' %}" />


<h2> Multiwavelength Page for Task {{taskname}}</h2>
<p>coordinate: {{ra}}, {{dec}}</p>
<p><b>note: due to vasttools compatibility, epochs after epoch12 are not supported </b></p>

<hr />
<p> Pipeline Run Match </p> 
{{vasttab | safe}}
<hr />
{% if isvast %}
<p> VAST lightcurve </p>
<img src="{{STATIC_PREFIX}}{{taskname}}/img/VASTlightcurve.png" width="60%">
<hr />
<p> archival data </p>
<img src="{{STATIC_PREFIX}}{{taskname}}/img/archival_lightcurve.png" width="66%">
<img src="{{STATIC_PREFIX}}{{taskname}}/img/wise-cc.png" width="22%">
<hr />

<p> VAST Stokes I (300 arcsec) </p>
<img src="{{STATIC_PREFIX}}{{taskname}}/img/StokesI_300.jpg" width="90%">
<p> VAST Stokes V (300 arcsec) </p>
<img src="{{STATIC_PREFIX}}{{taskname}}/img/StokesV_300.jpg" width="90%">
<hr />
{% endif %}
<p>Multiwavelength Cutouts</p>
{% for survey, path in overlaypath%}
<div class="multicutout">
    <p style="font-size: smaller;">{{survey}}</p>
    <img src="{{STATIC_PREFIX}}{{path}}" width="95%" />
    <!-- <img src="{% static 'multilambda/noimage.jpg' %}" onerror="this.onerror=null;this.src='{{STATIC_PREFIX}}{{taskname}}/img/{{survey}}_{{radius}}.png';" width="95%" /> -->
</div>
{% endfor %}

{% if not isvast %}
<hr />
<p> wise cc-plot </p>
<img src="{{STATIC_PREFIX}}{{taskname}}/img/wise-cc.png" width="30%">
{% endif %}

{% if isvast %}
<hr />
<p> VAST Stokes I (600 arcsec) </p>
<img src="{{STATIC_PREFIX}}{{taskname}}/img/StokesI_600.jpg" width="80%">
{% endif %}

<!-- 
    arguments used in this page
    - taskname
    - ra, dec
    - surveyjson

 -->